[package]
org = "chamil"
name = "petstore"
version = "0.1.0"

[build-options]
observabilityIncluded = false

[[platform.java11.dependency]]
artifactId = "mysql-connector-java"
version = "8.0.17"
path = "resources/mysql-connector-java-8.0.17.jar"
groupId = "mysql"